In [1]:
import numpy as np

# Numpy basics

In [2]:
my_array = [1,2,3,4,5]

In [3]:
np.array(my_array)

array([1, 2, 3, 4, 5])

In [4]:
type(my_array)

list

In [5]:
arr = np.array(my_array)

In [6]:
type(arr)

numpy.ndarray

In [7]:
a = np.arange(0,10)

In [8]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
b = np.arange(0,10,2)

In [10]:
b

array([0, 2, 4, 6, 8])

In [11]:
# 2D array also called a MATRIX

In [12]:
c = np.zeros((5,5))

In [13]:
c

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
# 1D array

In [15]:
d = np.zeros((1,10))

In [16]:
d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [17]:
e = np.zeros((2,10))

In [18]:
e

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
f = np.ones((2,4))

In [20]:
f

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
# Random arrays

In [24]:
np.random.randint(0,30)

2

In [25]:
rand_matrix = np.random.randint(0,100,(5,5))

In [26]:
rand_matrix

array([[90, 37, 41, 14, 21],
       [88, 37, 17, 23, 81],
       [89, 93, 84, 46, 34],
       [90, 20, 87,  4, 50],
       [47, 16, 36,  1, 29]])

In [27]:
np.linspace(0,50,10)

array([ 0.        ,  5.55555556, 11.11111111, 16.66666667, 22.22222222,
       27.77777778, 33.33333333, 38.88888889, 44.44444444, 50.        ])

In [28]:
np.linspace(0,10,101)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

### Numpy operations

In [30]:
np.random.seed(101)

In [31]:
np.random.randint(0,100,10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [32]:
# Finding the max,min,etc.

In [33]:
arr = np.random.randint(0,100,10)

In [34]:
arr

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [35]:
arr.max()

93

In [36]:
arr.min()

4

In [37]:
arr.mean()

47.3

In [38]:
arr.argmax()

8

In [39]:
arr.argmin()

0

### Reshape the array

In [40]:
arr.reshape(2,5)

array([[ 4, 63, 40, 60, 92],
       [64,  5, 12, 93, 40]])

### Indexing 

In [41]:
mat = np.arange(0,100).reshape(10,10)

In [42]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [43]:
mat[5,9]

59

In [45]:
mat[:,9]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [46]:
mat[5,:]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [48]:
mat[5,:].reshape(5,2)

array([[50, 51],
       [52, 53],
       [54, 55],
       [56, 57],
       [58, 59]])

### Masking

In [49]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [50]:
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [51]:
mat[mat > 50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])